name: Build and upload the container to GitHub Container Registry
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: public.ecr.aws/cds-snc/valentine
  IMAGE_NAME: valentine

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::283582579564:role/valentine-ecr-push-role-gh
          role-session-name: ValentineGitHubActions
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@5a88a04c91d5c6f97aae0d9be790e64d9b1d47b7 # v1.7.1
        with:
          registry-type: public

      - name: Build docker image
        working-directory: ./layer
        run: |
          docker build \ 
          -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA 
          -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push docker image to AWS ECR
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
          docker push $REGISTRY/$IMAGE_NAME:latest
