name: Lint, format and test code
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - valentine/**
      - .github/workflows/ci_code.yml

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2
          elixir-version: 1.18.1

      - name: Install dependencies
        run: |
          cd valentine && mix deps.get

      - name: Test and lint
        working-directory: ./valentine
        run: mix test && mix format --check-formatted
