name: Lint, format and test code

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - valentine/**
      - .github/workflows/ci_code.yml

jobs:
  tests:
    runs-on: ubuntu-24.04
    env:
      DATABASE_URL: "ecto://postgres:postgres@localhost"
      MIX_ENV: test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2
          elixir-version: 1.18.1

      - name: Install chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        working-directory: ./valentine
        run: mix deps.get

      - name: Compile dependencies
        working-directory: ./valentine
        run: mix deps.compile

      - name: Test and lint
        working-directory: ./valentine
        run: mix test && mix format --check-formatted
